print("Features of Python:")
print("\t1. Easy to Learn and Use")
print("\t\t- Simple syntax similar to English")
print("\t2. Interpreted Language")
print("\t\t- Executes code line by line")
print("\t3. Dynamically Typed")
print("\t\t- No need to declare variable types")
print("\t4. Extensive Libraries")
print("\t\t- Supports many built-in and third-party libraries")
print("\t5. Portable")
print("\t\t - Runs on different platforms without changes")
print("\t6. Object-Oriented")
print("\t\t- Supports classes and objects")
print("\t7. Open Source")
print("\t\t- Free to use and distribute")
print("\t8. High-level Language")
print("\t\t- Abstracts complex details from the programmer")
print("Start exploring Python today!")