#print(" I'm currrently learn computer Diploma from K.K.Wagh polytechnic ")
#print("""i am sumedh \n i am 18 years old \n i am study in third year of diploma in computer technology from K.K.wagh polytechnic nashik """)
#print("i am study in third year of diploma \n in computer technology from K.K.wagh polytechnic nashik ")
#print("name :- \n Roll No :- \n Division :-"

print("Features of Python:")
print("1. Easy to Learn and Use")
print("\t\t- Simple syntax similar to English")
print("2. Interpreted Language")
print("\t\t- Executes code line by line")
print("3. Dynamically Typed")
print("\t\t- No need to declare variable types")
print("4. Extensive Libraries")
print("\t\t- Supports many built-in and third-party libraries")
print("5. Portable")
print("\t\t - Runs on different platforms without changes")
print("6. Object-Oriented")
print("\t\t- Supports classes and objects")
print("7. Open Source")
print("\t\t- Free to use and distribute")
print("8. High-level Language")
print("\t\t- Abstracts complex details from the programmer")
print("Start exploring Python today!")